data:
  batch_size: 64
  max_length: 128
  path: data/yelp_reviews.json
hyperparameter_tuning:
  best_params:
    batch_size: 16
    dropout: 0.19825184780826133
    learning_rate: 0.004734664034654023
    optimizer: rmsprop
    weight_decay: 2.538226449992215e-05
  cv_folds: 3
  enabled: true
  n_epochs: 1
  n_trials: 5
model:
  dropout: 0.1
  pretrained_model: distilbert-base-cased
training:
  epochs: 10
  learning_rate: 1e-3
  optimizer: adamw
  scheduler: onecycle
  seed: 42
  weight_decay: 0.01
