# LSTM model configuration for Yelp sentiment analysis

# Data configuration
data:
  path: data/yelp_reviews.json
  max_length: 128
  max_vocab_size: 10000
  batch_size: 32
  tokenization_method: bpe  # Options: bpe, word

# Model architecture
model:
  embedding_dim: 128
  hidden_size: 64
  bidirectional: true
  dropout: 0.2
  use_attention: true

# Training configuration
training:
  epochs: 10
  optimizer: adam  # Options: adam, sgd, rmsprop, adamw
  learning_rate: 0.001
  weight_decay: 0.0
  scheduler: plateau  # Options: plateau, onecycle, none
  seed: 42

# Hyperparameter tuning
hyperparameter_tuning:
  enabled: false  # Set to true to perform hyperparameter tuning
  n_trials: 30
  cv_folds: 5
  # If hyperparameters have been tuned, their values will be stored here
  best_params: null
  # best_params:
  #   optimizer: adam
  #   learning_rate: 0.001
  #   weight_decay: 0.0001
  #   hidden_size: 128
  #   embedding_dim: 256
  #   dropout: 0.3
  #   bidirectional: true
  #   attention: true